name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v2.0.1)'
        required: true
        default: 'v2.0.0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: win
            artifact: 'Registro Contanti Setup *.exe'
          - os: macos-latest
            platform: mac
            artifact: 'Registro Contanti-*.dmg'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install frontend dependencies
      run: cd frontend && npm ci

    - name: Build frontend
      run: npm run build:frontend

    - name: Build application
      run: npm run build:${{ matrix.platform }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-build
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.version || github.ref_name }}
        name: Release ${{ github.event.inputs.version || github.ref_name }}
        body: |
          ## Registro Contanti ${{ github.event.inputs.version || github.ref_name }}
          
          ### Download
          - **Windows**: Scarica il file `.exe` per installare l'applicazione
          - **macOS**: Scarica il file `.dmg` per installare l'applicazione
          
          ### Installazione
          1. Scarica il file appropriato per il tuo sistema operativo
          2. Esegui il file di installazione
          3. Segui le istruzioni di installazione
          4. L'applicazione sarà disponibile nel menu Start/Applicazioni
          
          ### Note
          - L'applicazione include un database SQLite integrato
          - I dati vengono salvati localmente sul computer
          - Non è richiesta connessione internet per l'uso
        files: |
          artifacts/win-build/*
          artifacts/mac-build/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
