name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v2.0.1)'
        required: true
        default: 'v2.0.0'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: win
            artifact: 'Registro Contanti Setup *.exe'
          - os: macos-latest
            platform: mac
            artifact: 'Registro Contanti-*.dmg'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Rebuild native modules for Electron
      run: npx electron-rebuild

    - name: Install Windows build tools (Windows only)
      if: matrix.platform == 'win'
      run: npm install --global windows-build-tools

    - name: Install frontend dependencies
      run: cd frontend && npm ci

    - name: Build frontend
      run: npm run build:frontend

    - name: Build application
      run: npm run build:${{ matrix.platform }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.platform }}-build
        path: dist/

  # Release creation disabled - create manually on GitHub
  # The build artifacts are available in the Actions tab for download
